
version: "3"

services:
  app:
    image: nginx:latest
    links:
      - db
      - phpfpm
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/conf.d
      - appdata:/var/www/html
    ports:
      - 80:80
    networks: &appnetworks
      - www

  phpfpm:
    image: bunnyfeet/magento2-docker-php:latest
    links:
      - db
    volumes: 
      - appdata:/var/www/html
    networks: *appnetworks
    env_file: env/setup.env

  db:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306
    expose:
      - 3306
    networks: *appnetworks
    env_file: env/mysql.env

volumes:
  dbdata:
    driver_opts:
      type: none
      device: $PWD/db/data
      o: bind
  appdata:
    driver_opts:
      type: none
      device: $PWD/src/ce-2.2.0
      o: bind

networks:
  www:
