version: "3"

services:
  app:
    image: nginx:latest
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ./nginx/sites-enabled:/etc/nginx/conf.d
    ports:
      - 80
    networks: &appnetworks
      - www

  phpfpm:
    image: bunnyfeet/magento2-docker-php:7.1-fpm
    links:
      - db
    volumes: *appvolumes
    networks: *appnetworks
    env_file: env/setup.env

  db:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306
    networks: *appnetworks
    env_file: env/mysql.env

volumes:
  dbdata:
  appdata:

networks:
  www:
