
version: "3"

services:
  app:
    image: nginx:latest
    links:
      - db
      - phpfpm
    volumes: 
      - type: volume
        source: appdata
        target: /var/www/html
        volume:
          nocopy: true
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/conf.d
      - ./src/ce-2.2.0:/var/www/html
    ports:
      - 80:80
    networks: &appnetworks
      - www

  phpfpm:
    image: bunnyfeet/magento2-docker-php:latest
    links:
      - db
    volumes: 
      - ./src/ce-2.2.0:/var/www/html
    networks: *appnetworks
    env_file: env/setup.env

  db:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306
    networks: *appnetworks
    env_file: env/mysql.env

volumes:
  dbdata:
  appdata:

networks:
  www:
