
version: "3"

services:
  app:
    image: nginx:latest
    links:
      - db
      - phpfpm
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/conf.d
      - appdata:/var/www/html/magento2
      - ./magento/app:/var/www/html/magento2/app
    ports:
      - 80:80
    networks: &appnetworks
      - www
    depends_on:
      - phpfpm

  phpfpm:
    #build:
    #  context: .
    #  dockerfile: "Dockerfile-php"
    image: bunnyfeet/magento2-docker-php:7.1-fpm
    links:
      - db
    volumes: 
      - appdata:/var/www/html/magento2
      - ./auth.json:/home/root/.composer/auth.json
      - ./magento/app/code:/var/www/html/magento2/app/code
      - ./magento/app/design:/var/www/html/magento2/app/design
      - cache:/cache
    networks: *appnetworks
    env_file: env/setup.env

  db:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306
    expose:
      - 3306
    networks: *appnetworks
    env_file: env/mysql.env

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks: *appnetworks

volumes:
  appdata:
  dbdata:
  cache:
networks:
  www:
