
version: "3"

services:
  app:
    image: nginx:latest
    links:
      - db
      - phpfpm
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/conf.d
      - appdata:/var/www/html/magento2
    ports:
      - 80:80
    networks: &appnetworks
      - www
    depends_on:
      - phpfpm

  phpfpm:
    build:
      context: .
      dockerfile: "Dockerfile-php"
    links:
      - db
    volumes: 
      - appdata:/var/www/html/magento2
      - cache:/cache
    networks: *appnetworks
    env_file: env/setup.env

  db:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306
    expose:
      - 3306
    networks: *appnetworks
    env_file: env/mysql.env

volumes:
  dbdata:
  appdata:
  cache:
networks:
  www:
